version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          - POSTGRES_DB=elschool_api_db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    elschool_api-container:
        image: ghcr.io/userver-framework/ubuntu-userver-build-base:v1
        privileged: true
        environment:
          - POSTGRES_DB=elschool_api_db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CC
          - CCACHE_DIR=/elschool_api/.ccache
          - CCACHE_HASHDIR
          - CCACHE_NOHASHDIR
          - CCACHE_PREFIX
          - CCACHE_SIZE
          - CMAKE_OPTS
          - CORES_DIR=/cores
          - CXX
          - MAKE_OPTS
          - CMAKE_COMMON_FLAGS
          - TZ=Asia/Yekaterinburg
        volumes:
          - .:/elschool_api:rw
          - ./third_party/userver/tools/docker:/tools:ro
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /elschool_api
        entrypoint:
          - /tools/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
