worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: true

# elschool_api_db_1 is the service name + _ + filename of the db_1.sql
dbconnection: 'postgresql://testsuite@localhost:15433/elschool_api_db_1'
